### ISSUE TITLE
how can I find status of acceptance into git core?

### ISSUE THREAD

**Issue by cleeland** [jonseymour/gitwork#1]
I'm curious as to the status of acceptance of this proposal into the git core.  How can I find out?

**Comment by jonseymour** [comment]
G'day Chris,

Thanks for your interest - I haven't made a serious attempt to get the proposal accepted into git-core at this point.  

jon.

**Comment by cleeland** [comment]
On Sat, Aug 3, 2013 at 5:59 AM, jonseymour notifications@github.com wrote:

> G'day Chris,
> 
> Thanks for your interest - I haven't made a serious attempt to get the
> proposal accepted into git-core at this point.

Ah, oh well. I was interested in using it to build some internal tools.  I
think I found a way to do what I need without gitwork, but it would be nice
to see this appear in the real deal.

Cheers,
-cj

## 

Chris Cleeland

**Comment by jonseymour** [comment]
Chris,

Am interested to know which feature of the gitwork toolset you find most useful and what problems it is solving for you. And, on the other hand, things you would change if you could?

jon.

**Comment by cleeland** [comment]
I don't have enough working experience to know what I would change other
than maybe clarify the documentation with more examples.

In terms of what I think I would find most useful...the workflow I need to
support requires maintaining several concurrent branches of different
versions of software. A frequent use case is to have to port a change
mademon a topic brnach to most or all of these branches. A merge does not
work since that drags in more than just the changes. Rebase works, but
requires knowing the start and end commits of the topic branch.

From the docs, it sounds as if gitwork manages tracking the start/end
commits of a topic branch as well as providing other tools that will aid in
transplantation. It also sounds like it provides tools to enforce
installation-defined branch invariants, eg, every commit on branch "x" must
compile and pass unit tests.

I may not be understanding though.

On Sunday, August 4, 2013, jonseymour wrote:

> Chris,
> 
> Am interested to know which feature of the gitwork toolset you find most
> useful and what problems it is solving for you. And, on the other hand,
> things you would change if you could?
> 
> jon.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jonseymour/gitwork/issues/1#issuecomment-22069828
> .

## 

Chris Cleeland

**Comment by jonseymour** [comment]
Chris,

So, it does sound like your use case requires topic branches. Ultimately, I think you do need to use merging to share code between different versions of your software. The key to make merging work is to make sure the "base" of your topic branch is a single commit shared by all your maintenance branches. If this is true, then a merge of the topic will drag in the topic and only the topic.

Using rebase or cherry-pick works for this purpose might work in the short-term but ultimately causes divergence between the maintenance branches which is extremely difficult to reconcile.

To make merging work, you ideally need to make sure _all_ integration into your maintenance branches is done by merge from isolated topic branches - that is, don't ever commit directly onto the maintenance branch. Only in this way can you maximise the chance that you can share that fix with another maintenance branch by merging the topic that contains the fix. You will note that git's own master branch is maintained in this way.

Note also, that this isn't a silver bullet. Eventually you will find a fix that you need to make that can't be cleanly merged into all downstream maintenance branches because the files changed by the topic have separately diverged on other topics. In cases like this, you need to find the conflicting topics, create a branch to resolve the conflicts and then merge that resolution into the downstream maintenance branches. 

So, git-work helps by allowing you to effectively manage topic based development. It does this by providing each developer with their own, private, integration branch which represents the union of all topic branches plus unreleased changes. The tools provide a way of incrementally releasing unreleased work onto topic branches which are then shared with others/merged into the maintenance branches. In this case, developers retain the convenience of a single integration branch, but the maintain the flexibility of topic based development.

To clear up a potential misunderstanding - git work doesn't support installation-defined branch invariants. There is mention of invariants in the documentation, but that is an invariant internal to the specification of the 'git-base' command which is used to track the "base" of the user's working(/integration) branch

**Comment by cleeland** [comment]
On Sun, Aug 4, 2013 at 3:31 PM, jonseymour notifications@github.com wrote:

> Chris,
> 
> So, it does sound like your use case requires topic branches. Ultimately,
> I think you do need to use merging to share code between different versions
> of your software. The key to make merging work is to make sure the "base"
> of your topic branch is a single commit shared by all your maintenance
> branches. If this is true, then a merge of the topic will drag in the topic
> and only the topic.
> 
> I'm not sure how it's possible for the base of all maintenance branches to
> be the same.  By definition, the base of a maintenance branch is a going to
> be the base of a particular revision/release of the software.  Version 2.0
> and 1.0 will have very different "base" revisions.  They will have a common
> base far enough back in the tree, but a merge of a topic into Version 2.0,
> followed by a merge of "topic" into Version 1.0 would end up making Version
> 1.0 and Version 2.0 the same.  At least that's what happened when I
> actually tried it.
> 
> To make merging work, you ideally need to make sure _all_ integration
> into your maintenance branches is done by merge from isolated topic branches
> 
> Once you merge the topic branch to a maintenance branch, the topic branch
> becomes the maintenance branch. I'm not sure how what you're suggesting
> works.

So, git-work helps by allowing you to effectively manage topic based

> development. It does this by providing each developer with their own,
> private, integration branch which represents the union of all topic
> branches plus unreleased changes. The tools provide a way of incrementally
> releasing unreleased work onto topic branches which are then shared with
> others/merged into the maintenance branches. In this case, developers
> retain the convenience of a single integration branch, but the maintain the
> flexibility of topic based development.
> 
> Hmmm...that's very different from the impression I got from reading the
> docs.  Obviously I'm not telling you you're wrong, but thought I'd point
> out how I've misunderstood.
> 
> To clear up a potential misunderstanding - git work doesn't support
> installation-defined branch invariants. There is mention of invariants in
> the documentation, but that is an invariant internal to the specification
> of the 'git-base' command which is used to track the "base" of the user's
> working(/integration) branch
> 
> Oh.  Bummer, because that would be really cool.

## 

Chris Cleeland

**Comment by jonseymour** [comment]
| amended some typos and other errors

Chris,

> I'm not sure how it's possible for the base of all maintenance branches to
> be the same.  By definition, the base of a maintenance branch is a going to
> be the base of a particular revision/release of the software.  Version 2.0
> and 1.0 will have very different "base" revisions.  They will have a common
> base far enough back in the tree, but a merge of a topic into Version 2.0,
> followed by a merge of "topic" into Version 1.0 would end up making Version
> 1.0 and Version 2.0 the same.  At least that's what happened when I
> actually tried it.

You are correct that Version 2.0 will have and Version 1.0 will have different base versions. However, presumably version 1.0 and version 2.0 shared a common commit in the past. This may be V1.0.0 or it might be, V0.9.x. 
The important thing isn't the base of the maintenance branches - it is the base of the topic branches that you want to apply to both maintenance branches.

Suppose the maintenance branches for V1.x and V2.x are called V1 and V2 respectively.

First, calculate the merge-base between V1 and V2 - this is a commit common to both V1 and V2 - call this commit B. 

First, create a throw-away branch from the tip of V1 - call this T. Use this to develop and test the fix to V1. Now, try to rebase V1..T onto B to produce T'. If this works cleanly, then the changes in V1..T (probably) only depend on B. Merge T' into V1 and call this V1'. V1' should be tree-same to T.

Now, try to merge T' into V2, call this V2'. This might not work cleanly if V2 has modified the files in T since B. However, if it does work, then V2'  will basically be V2 + T' which is the desired result - it hasn't dragged in any other change to V1 since B.

Now, things aren't guaranteed to produce a smooth result. If either V1 or V2 have modified the files in T' since B then either the initial rebase of T onto B or the merge of T' into V2 will fail. However, in the case of conflict detected during rebase, the fix is often as simple as identifying which earlier topic branches T depends on and, instead of rebasing T onto B, rebasing T onto a merge of B and the (topic) branches containing those particular dependencies.

Again, even this isn't perfect since this may still create a T' that contains changes in V1 that you don't want in V2. 

So, this isn't a solution for cases where you want to allow arbitrary divergence of V1 from V2. It may be a solution for cases where you allow V2 to diverge from V1 but you want V2 to benefit from fixes made to V1.
